# Generated by Django 4.2.7 on 2023-12-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_sent_for_editing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='sent_for_edit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/newsletter.jpg', upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/newsletter.jpg', upload_to='thumbnails/'),
        ),
    ]
